import { defineConfig } from "orval";

export default defineConfig({
  waitlistApi: {
    input: {
      target: process.env.VITE_SWAGGER_URL || "https://waitlist.cedradev.xyz/api/api-tools/docs-json",
    },
    hooks: {
      afterAllFilesWrite: "tsx src/lib/api/scripts/post-orval.mjs",
    },
    output: {
      target: "./src/lib/api/generated",
      schemas: "./src/lib/api/generated/model",
      client: "react-query",
      mode: "tags-split",
      clean: true,
      prettier: true,
      indexFiles: true,
      baseUrl: {
        getBaseUrlFromSpecification: false,
        baseUrl: "",
      },
      override: {
        mutator: {
          path: "./src/lib/api/client/orvalMutator.ts",
          name: "orvalMutator",
        },
        query: {
          version: 5,
          shouldSplitQueryKey: true,
          signal: true,
        },
        header: () => ["/* eslint-disable */", "// --- AUTO-GENERATED BY ORVAL ---"],
      },
    },
  },
});