import { config } from 'dotenv';
import { defineConfig } from 'orval';

// Load environment variables from .env file
config();

export default defineConfig({
  waitlistApi: {
    input: {
      target: process.env.VITE_SWAGGER_URL ?? 'http://localhost:3000/api-json',
    },
    hooks: {
      afterAllFilesWrite: 'tsx src/lib/api/scripts/post-orval.mjs',
    },
    output: {
      target: './src/lib/api/generated',
      schemas: './src/lib/api/generated/model',
      client: 'react-query',
      mode: 'tags-split',
      clean: true,
      prettier: false,
      indexFiles: true,
      baseUrl: {
        getBaseUrlFromSpecification: false,
        baseUrl: '',
      },
      override: {
        mutator: {
          path: './src/lib/api/client/authenticatedMutator.ts',
          name: 'authenticatedMutator',
        },
        query: {
          version: 5,
          shouldSplitQueryKey: true,
          signal: true,
        },
        header: () => [
          '/* eslint-disable */',
          '/* cSpell:disable */',
          '// --- AUTO-GENERATED BY ORVAL ---',
        ],
      },
    },
  },
});
