import { config } from 'dotenv';
import { defineConfig } from 'orval';

// Load environment variables from .env file
config();

export default defineConfig({
  waitlistApi: {
    input: {
      target: process.env.VITE_SWAGGER_URL ?? 'http://localhost:3000/api-json',
      // Disable strict validation until API is fixed
      validation: false,
    },
    hooks: {
      afterAllFilesWrite: 'tsx src/lib/api/scripts/post-orval.mjs',
    },
    output: {
      target: './src/lib/api/generated',
      schemas: './src/lib/api/generated/model',
      client: 'react-query',
      mode: 'tags-split',
      clean: true,
      prettier: false,
      indexFiles: true,

      // Fixed: Simplified baseUrl (avoids TypeScript bug #1787)
      baseUrl: '',

      override: {
        mutator: {
          path: './src/lib/api/client/authenticatedMutator.ts',
          name: 'authenticatedMutator',
        },

        // Full configuration for React Query v5
        query: {
          version: 5,
          shouldSplitQueryKey: true,
          signal: true,
        },

        // Enhanced headers with metadata
        header: (info) => [
          '/* eslint-disable */',
          '/* cSpell:disable */',
          `// --- AUTO-GENERATED BY ORVAL v${info?.version || 'unknown'} ---`,
          `// Generated: ${new Date().toISOString()}`,
          '// ⚠️  DO NOT EDIT MANUALLY',
          '',
        ],
      },
    },
  },
});
