/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuestsIndexRouteImport } from './routes/quests/index'
import { Route as QuestsNewRouteImport } from './routes/quests/new'
import { Route as Quests_layoutRouteImport } from './routes/quests/__layout'
import { Route as QuestsIdRouteImport } from './routes/quests/$id'

const QuestsRouteImport = createFileRoute('/quests')()

const QuestsRoute = QuestsRouteImport.update({
  id: '/quests',
  path: '/quests',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestsIndexRoute = QuestsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => QuestsRoute,
} as any)
const QuestsNewRoute = QuestsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => QuestsRoute,
} as any)
const Quests_layoutRoute = Quests_layoutRouteImport.update({
  id: '/__layout',
  getParentRoute: () => QuestsRoute,
} as any)
const QuestsIdRoute = QuestsIdRouteImport.update({
  id: '/quests/$id',
  path: '/quests/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/quests/$id': typeof QuestsIdRoute
  '/quests': typeof Quests_layoutRoute
  '/quests/new': typeof QuestsNewRoute
  '/quests/': typeof QuestsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/quests/$id': typeof QuestsIdRoute
  '/quests': typeof QuestsIndexRoute
  '/quests/new': typeof QuestsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/quests/$id': typeof QuestsIdRoute
  '/quests': typeof QuestsRouteWithChildren
  '/quests/__layout': typeof Quests_layoutRoute
  '/quests/new': typeof QuestsNewRoute
  '/quests/': typeof QuestsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/quests/$id' | '/quests' | '/quests/new' | '/quests/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/quests/$id' | '/quests' | '/quests/new'
  id:
    | '__root__'
    | '/'
    | '/quests/$id'
    | '/quests'
    | '/quests/__layout'
    | '/quests/new'
    | '/quests/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  QuestsIdRoute: typeof QuestsIdRoute
  QuestsRoute: typeof QuestsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/quests': {
      id: '/quests'
      path: '/quests'
      fullPath: '/quests'
      preLoaderRoute: typeof QuestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quests/': {
      id: '/quests/'
      path: '/'
      fullPath: '/quests/'
      preLoaderRoute: typeof QuestsIndexRouteImport
      parentRoute: typeof QuestsRoute
    }
    '/quests/new': {
      id: '/quests/new'
      path: '/new'
      fullPath: '/quests/new'
      preLoaderRoute: typeof QuestsNewRouteImport
      parentRoute: typeof QuestsRoute
    }
    '/quests/__layout': {
      id: '/quests/__layout'
      path: '/quests'
      fullPath: '/quests'
      preLoaderRoute: typeof Quests_layoutRouteImport
      parentRoute: typeof QuestsRoute
    }
    '/quests/$id': {
      id: '/quests/$id'
      path: '/quests/$id'
      fullPath: '/quests/$id'
      preLoaderRoute: typeof QuestsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface QuestsRouteChildren {
  Quests_layoutRoute: typeof Quests_layoutRoute
  QuestsNewRoute: typeof QuestsNewRoute
  QuestsIndexRoute: typeof QuestsIndexRoute
}

const QuestsRouteChildren: QuestsRouteChildren = {
  Quests_layoutRoute: Quests_layoutRoute,
  QuestsNewRoute: QuestsNewRoute,
  QuestsIndexRoute: QuestsIndexRoute,
}

const QuestsRouteWithChildren =
  QuestsRoute._addFileChildren(QuestsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  QuestsIdRoute: QuestsIdRoute,
  QuestsRoute: QuestsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
