/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as QuestsRoutesRouteImport } from './routes/quests.routes'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestsRoutesRoute = QuestsRoutesRouteImport.update({
  id: '/quests/routes',
  path: '/quests/routes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/quests/routes': typeof QuestsRoutesRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/quests/routes': typeof QuestsRoutesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/login': typeof LoginRoute
  '/quests/routes': typeof QuestsRoutesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/login' | '/quests/routes'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/quests/routes'
  id: '__root__' | '/login' | '/quests/routes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LoginRoute: typeof LoginRoute
  QuestsRoutesRoute: typeof QuestsRoutesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quests/routes': {
      id: '/quests/routes'
      path: '/quests/routes'
      fullPath: '/quests/routes'
      preLoaderRoute: typeof QuestsRoutesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  LoginRoute: LoginRoute,
  QuestsRoutesRoute: QuestsRoutesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
